<AccessPage>:
	orientation: 'lr-tb'
	spacing: 3
	padding: 10

	AnchorLayout:
		size_hint: 1, 0.03
		anchor_x: 'center'
		anchor_y: 'top'
		Label:
			color: [105, 106, 188, 1]
			halign: 'left'
			text: "--Upload a file to the database server's file system--"

	AnchorLayout:
		size_hint: 1, 0.03
		anchor_x: 'center'
		anchor_y: 'top'
		Label:
			text: 'Эти опции могут быть использованы для доступа к файловой системе СУБД'

	AnchorLayout:
		size_hint: 1, 0.03
		anchor_x: 'center'
		anchor_y: 'top'
		Label:

	# -file-read
	BoxLayout:
		size_hint: 0.2, 0.05
		spacing: 3
		AnchorLayout:
			anchor_x: 'left'
			anchor_y: 'center'
			size_hint: 0.2, 1
			CheckBox:
				on_active: root.access_page_to_dict(self.active, '--file-read')
		AnchorLayout:
			anchor_x: 'center'
			anchor_y: 'center'
			size_hint: 0.2, 1
			Button:
				background_color: 0, 0, 1
				text: '?'
				on_release: root.show_help_string('--file-read')
		AnchorLayout:
			anchor_x: 'right'
			anchor_y: 'center'
			size_hint: 0.6, 1
			Button:
				text: 'first'
				on_release: root.add_input_text('--file-read')

	# -file-write
	BoxLayout:
		size_hint: 0.2, 0.05
		spacing: 3
		AnchorLayout:
			anchor_x: 'left'
			anchor_y: 'center'
			size_hint: 0.2, 1
			CheckBox:
				on_active: root.access_page_to_dict(self.active, '--file-write')
		AnchorLayout:
			anchor_x: 'center'
			anchor_y: 'center'
			size_hint: 0.2, 1
			Button:
				background_color: 0, 0, 1
				text: '?'
				on_release: root.show_help_string('--file-write')
		AnchorLayout:
			anchor_x: 'right'
			anchor_y: 'center'
			size_hint: 0.6, 1
			Button:
				text: 'file-write'
				on_release: root.add_input_text('--file-write')

	# -file-dest
	BoxLayout:
		size_hint: 0.2, 0.05
		spacing: 3
		AnchorLayout:
			anchor_x: 'left'
			anchor_y: 'center'
			size_hint: 0.2, 1
			CheckBox:
				on_active: root.access_page_to_dict(self.active, '--file-dest')
		AnchorLayout:
			anchor_x: 'center'
			anchor_y: 'center'
			size_hint: 0.2, 1
			Button:
				background_color: 0, 0, 1
				text: '?'
				on_release: root.show_help_string('--file-dest')
		AnchorLayout:
			anchor_x: 'right'
			anchor_y: 'center'
			size_hint: 0.6, 1
			Button:
				text: 'file-dest'
				on_release: root.add_input_text('--file-dest')


	AnchorLayout:
		size_hint: 1, 0.03
		anchor_x: 'center'
		anchor_y: 'top'
		Label:
			color: [105, 106, 188, 1]
			halign: 'left'
			text: "--Operating system takeover--"

	AnchorLayout:
		size_hint: 1, 0.03
		anchor_x: 'center'
		anchor_y: 'top'
		Label:
			text: 'Эти опции могут быть использованы для получения доступа к ОС СУБД'

	AnchorLayout:
		size_hint: 1, 0.03
		anchor_x: 'center'
		anchor_y: 'top'
		Label:

	# --os-cmd
	BoxLayout:
		size_hint: 0.2, 0.05
		spacing: 3
		AnchorLayout:
			anchor_x: 'left'
			anchor_y: 'center'
			size_hint: 0.2, 1
			CheckBox:
				on_active: root.access_page_to_dict(self.active, '--os-cmd')
		AnchorLayout:
			anchor_x: 'center'
			anchor_y: 'center'
			size_hint: 0.2, 1
			Button:
				background_color: 0, 0, 1
				text: '?'
				on_release: root.show_help_string('--os-cmd')
		AnchorLayout:
			anchor_x: 'right'
			anchor_y: 'center'
			size_hint: 0.6, 1
			Button:
				text: 'os-cmd'
				on_release: root.add_input_text('--os-cmd')

	# --os-shell
	BoxLayout:
		size_hint: 0.2, 0.05
		spacing: 3
		AnchorLayout:
			anchor_x: 'left'
			anchor_y: 'center'
			size_hint: 0.2, 1
			CheckBox:
				on_active: root.access_page_to_dict(self.active, '--os-shell')
		AnchorLayout:
			anchor_x: 'center'
			anchor_y: 'center'
			size_hint: 0.2, 1
			Button:
				background_color: 0, 0, 1
				text: '?'
				on_release: root.show_help_string('--os-shell')
		AnchorLayout:
			anchor_x: 'right'
			anchor_y: 'center'
			size_hint: 0.6, 1
			Label:
				text: 'os-shell'

	# --os-pwn
	BoxLayout:
		size_hint: 0.2, 0.05
		spacing: 3
		AnchorLayout:
			anchor_x: 'left'
			anchor_y: 'center'
			size_hint: 0.2, 1
			CheckBox:
				on_active: root.access_page_to_dict(self.active, '--os-pwn')
		AnchorLayout:
			anchor_x: 'center'
			anchor_y: 'center'
			size_hint: 0.2, 1
			Button:
				background_color: 0, 0, 1
				text: '?'
				on_release: root.show_help_string('--os-pwn')
		AnchorLayout:
			anchor_x: 'right'
			anchor_y: 'center'
			size_hint: 0.6, 1
			Label:
				text: 'os-pwn'

	# --os-smbrelay
	BoxLayout:
		size_hint: 0.2, 0.05
		spacing: 3
		AnchorLayout:
			anchor_x: 'left'
			anchor_y: 'center'
			size_hint: 0.2, 1
			CheckBox:
				on_active: root.access_page_to_dict(self.active, '--os-smbrelay')
		AnchorLayout:
			anchor_x: 'center'
			anchor_y: 'center'
			size_hint: 0.2, 1
			Button:
				background_color: 0, 0, 1
				text: '?'
				on_release: root.show_help_string('--os-smbrelay')
		AnchorLayout:
			anchor_x: 'right'
			anchor_y: 'center'
			size_hint: 0.6, 1
			Label:
				text: 'os-smbrelay'

	# --os-bof
	BoxLayout:
		size_hint: 0.2, 0.05
		spacing: 3
		AnchorLayout:
			anchor_x: 'left'
			anchor_y: 'center'
			size_hint: 0.2, 1
			CheckBox:
				on_active: root.access_page_to_dict(self.active, '--os-bof')
		AnchorLayout:
			anchor_x: 'center'
			anchor_y: 'center'
			size_hint: 0.2, 1
			Button:
				background_color: 0, 0, 1
				text: '?'
				on_release: root.show_help_string('--os-bof')
		AnchorLayout:
			anchor_x: 'right'
			anchor_y: 'center'
			size_hint: 0.6, 1
			Label:
				text: 'os-bof'

	# --priv-esc
	BoxLayout:
		size_hint: 0.2, 0.05
		spacing: 3
		AnchorLayout:
			anchor_x: 'left'
			anchor_y: 'center'
			size_hint: 0.2, 1
			CheckBox:
				on_active: root.access_page_to_dict(self.active, '--priv-esc')
		AnchorLayout:
			anchor_x: 'center'
			anchor_y: 'center'
			size_hint: 0.2, 1
			Button:
				background_color: 0, 0, 1
				text: '?'
				on_release: root.show_help_string('--priv-esc')
		AnchorLayout:
			anchor_x: 'right'
			anchor_y: 'center'
			size_hint: 0.6, 1
			Label:
				text: 'priv-esc'

	# --msf-path
	BoxLayout:
		size_hint: 0.2, 0.05
		spacing: 3
		AnchorLayout:
			anchor_x: 'left'
			anchor_y: 'center'
			size_hint: 0.2, 1
			CheckBox:
				on_active: root.access_page_to_dict(self.active, '--msf-path')
		AnchorLayout:
			anchor_x: 'center'
			anchor_y: 'center'
			size_hint: 0.2, 1
			Button:
				background_color: 0, 0, 1
				text: '?'
				on_release: root.show_help_string('--msf-path')
		AnchorLayout:
			anchor_x: 'right'
			anchor_y: 'center'
			size_hint: 0.6, 1
			Button:
				text: 'msf-path'
				on_release: root.show_files_path('--msf-path')

	# --tmp-path
	BoxLayout:
		size_hint: 0.2, 0.05
		spacing: 3
		AnchorLayout:
			anchor_x: 'left'
			anchor_y: 'center'
			size_hint: 0.2, 1
			CheckBox:
				on_active: root.access_page_to_dict(self.active, '--tmp-path')
		AnchorLayout:
			anchor_x: 'center'
			anchor_y: 'center'
			size_hint: 0.2, 1
			Button:
				background_color: 0, 0, 1
				text: '?'
				on_release: root.show_help_string('--tmp-path')
		AnchorLayout:
			anchor_x: 'right'
			anchor_y: 'center'
			size_hint: 0.6, 1
			Button:
				text: 'tmp-path'
				on_release: root.show_files_path('--tmp-path')

	AnchorLayout:
		size_hint: 1, 0.03
		anchor_x: 'center'
		anchor_y: 'top'
		Label:
			color: [105, 106, 188, 1]
			halign: 'left'
			text: "--Windows registry access--"

	AnchorLayout:
		size_hint: 1, 0.03
		anchor_x: 'center'
		anchor_y: 'top'
		Label:
			text: 'Эти опции могут использоваться к доступу к регистру Windows СУБД'

	AnchorLayout:
		size_hint: 1, 0.03
		anchor_x: 'center'
		anchor_y: 'top'
		Label:

	# --reg-read
	BoxLayout:
		size_hint: 0.2, 0.05
		spacing: 3
		AnchorLayout:
			anchor_x: 'left'
			anchor_y: 'center'
			size_hint: 0.2, 1
			CheckBox:
				on_active: root.access_page_to_dict(self.active, '--reg-read')
		AnchorLayout:
			anchor_x: 'center'
			anchor_y: 'center'
			size_hint: 0.2, 1
			Button:
				background_color: 0, 0, 1
				text: '?'
				on_release: root.show_help_string('--reg-read')
		AnchorLayout:
			anchor_x: 'right'
			anchor_y: 'center'
			size_hint: 0.6, 1
			Label:
				text: 'reg-read'

	# --reg-add
	BoxLayout:
		size_hint: 0.2, 0.05
		spacing: 3
		AnchorLayout:
			anchor_x: 'left'
			anchor_y: 'center'
			size_hint: 0.2, 1
			CheckBox:
				on_active: root.access_page_to_dict(self.active, '--reg-add')
		AnchorLayout:
			anchor_x: 'center'
			anchor_y: 'center'
			size_hint: 0.2, 1
			Button:
				background_color: 0, 0, 1
				text: '?'
				on_release: root.show_help_string('--reg-add')
		AnchorLayout:
			anchor_x: 'right'
			anchor_y: 'center'
			size_hint: 0.6, 1
			Label:
				text: 'reg-add'

	# --reg-del
	BoxLayout:
		size_hint: 0.2, 0.05
		spacing: 3
		AnchorLayout:
			anchor_x: 'left'
			anchor_y: 'center'
			size_hint: 0.2, 1
			CheckBox:
				on_active: root.access_page_to_dict(self.active, '--reg-del')
		AnchorLayout:
			anchor_x: 'center'
			anchor_y: 'center'
			size_hint: 0.2, 1
			Button:
				background_color: 0, 0, 1
				text: '?'
				on_release: root.show_help_string('--reg-del')
		AnchorLayout:
			anchor_x: 'right'
			anchor_y: 'center'
			size_hint: 0.6, 1
			Label:
				text: 'reg-del'

	# --reg-key
	BoxLayout:
		size_hint: 0.2, 0.05
		spacing: 3
		AnchorLayout:
			anchor_x: 'left'
			anchor_y: 'center'
			size_hint: 0.2, 1
			CheckBox:
				on_active: root.access_page_to_dict(self.active, '--reg-key')
		AnchorLayout:
			anchor_x: 'center'
			anchor_y: 'center'
			size_hint: 0.2, 1
			Button:
				background_color: 0, 0, 1
				text: '?'
				on_release: root.show_help_string('--reg-key')
		AnchorLayout:
			anchor_x: 'right'
			anchor_y: 'center'
			size_hint: 0.6, 1
			Button:
				text: 'reg-key'
				on_release: root.add_input_text('--reg-key')

	# --reg-value
	BoxLayout:
		size_hint: 0.2, 0.05
		spacing: 3
		AnchorLayout:
			anchor_x: 'left'
			anchor_y: 'center'
			size_hint: 0.2, 1
			CheckBox:
				on_active: root.access_page_to_dict(self.active, '--reg-value')
		AnchorLayout:
			anchor_x: 'center'
			anchor_y: 'center'
			size_hint: 0.2, 1
			Button:
				background_color: 0, 0, 1
				text: '?'
				on_release: root.show_help_string('--reg-value')
		AnchorLayout:
			anchor_x: 'right'
			anchor_y: 'center'
			size_hint: 0.6, 1
			Button:
				text: 'reg-value'
				on_release: root.add_input_text('--reg-value')

	# --reg-data
	BoxLayout:
		size_hint: 0.2, 0.05
		spacing: 3
		AnchorLayout:
			anchor_x: 'left'
			anchor_y: 'center'
			size_hint: 0.2, 1
			CheckBox:
				on_active: root.access_page_to_dict(self.active, '--reg-data')
		AnchorLayout:
			anchor_x: 'center'
			anchor_y: 'center'
			size_hint: 0.2, 1
			Button:
				background_color: 0, 0, 1
				text: '?'
				on_release: root.show_help_string('--reg-data')
		AnchorLayout:
			anchor_x: 'right'
			anchor_y: 'center'
			size_hint: 0.6, 1
			Button:
				text: 'reg-data'
				on_release: root.add_input_text('--reg-data')

	# --reg-type
	BoxLayout:
		size_hint: 0.2, 0.05
		spacing: 3
		AnchorLayout:
			anchor_x: 'left'
			anchor_y: 'center'
			size_hint: 0.2, 1
			CheckBox:
				on_active: root.access_page_to_dict(self.active, '--reg-type')
		AnchorLayout:
			anchor_x: 'center'
			anchor_y: 'center'
			size_hint: 0.2, 1
			Button:
				background_color: 0, 0, 1
				text: '?'
				on_release: root.show_help_string('--reg-type')
		AnchorLayout:
			anchor_x: 'right'
			anchor_y: 'center'
			size_hint: 0.6, 1
			Button:
				text: 'reg-type'
				on_release: root.add_input_text('--reg-type')