#:kivy 2.0.0
#:include request_page.kv
#:include optimisation_page.kv
#:include injection_page.kv
#:include detection_page.kv
#:include techniques_page.kv
#:include enumeration_page.kv
#:include broot_func_page.kv
#:include access_page.kv
#:include general_page.kv
#:include miscellaneous_page.kv

#Панель с вкладками
<TabbedPanelMain>:
    do_default_tab: False

    TabbedPanelItem:
        text: 'Запросы'
        RequestsPage:
    TabbedPanelItem:
        text: 'Оптимизация'
        OptimisationPage:
    TabbedPanelItem:
        text: 'Инекция'
        InjectionPage:
    TabbedPanelItem:
        text: 'Выявление'
        DetectionPage:
    TabbedPanelItem:
        text: 'Техники'
        TechniquesPage:
    TabbedPanelItem:
        text: 'Перечисления'
        EnumerationPage:
    TabbedPanelItem:
        text: 'Брут и\nФункции'
        BrootFuncPage:
    TabbedPanelItem:
        text: 'Доступ'
        AccessPage:
    TabbedPanelItem:
        text: 'Общие'
        GeneralPage:
    TabbedPanelItem:
        text: 'Разное'
        MiscellaneousPage:


#всплывающее окно с выбором файла
<LoadFileTarget>:
    BoxLayout:
        size: root.size
        pos: root.pos
        orientation: "vertical"
#        сам виджет с файлами
        FileChooserListView:
            id: filechooser
#            при выборе, вызываем функцию для записи выбора в строку URL
            on_selection: root.selected_file_target(filechooser.selection)

        BoxLayout:
            size_hint_y: None
            height: 30
            Button:
                text: "Ok"
#                при нажатии на кнопку закрывает всплывающее окно
                on_release: root.cancel()

<ErrorPage>:
	error_lable: error_lable
	BoxLayout:
        size: root.size
        pos: root.pos
        orientation: "vertical"
        Label:
            id: error_lable
            text: 'Ошибка'

        BoxLayout:
            size_hint_y: None
            height: 30
            Button:
                text: "Ok"
#                при нажатии на кнопку закрывает всплывающее окно
                on_release: root.cancel()

<ResultPage>:
	result_lable: result_lable
	BoxLayout:
        size: root.size
        pos: root.pos
        orientation: "vertical"
        CodeInput:
            id: result_lable

        BoxLayout:
            size_hint_y: None
            height: 40
            spacing: 2
            padding: 2
            Button:
                text: "Закрыть"
                background_color: 1, 0, 0
                on_release: root.cancel()
            Button:
                background_color: 0, 0, 1
                text: "Копировать"
                on_release: root.copy_result_out()
            Button:
                background_color: 0, 1, 0
                text: "Выполнить"
                on_release: root.execute_command()


#контейнер основной программы
<MainContainer>:

	orientation: 'vertical'
	padding: 10 #Внутренние отступы объекта
	spacing: 10 #Расстояние между объектами

#	связь функция: ID  связь программы с ID виджетов
#	выподающее меню в районе адреса цели
	spiner_target_data: spiner_target
#	надпись над полем ввода цели
	lable_on_target: lable_on_target
#	поле ввода для цели
	input_target: input_target

	BoxLayout:
		size_hint: 1, 0.15
		spacing: 10

		BoxLayout:
			padding: 20
			size_hint: 0.3, 1
#			выподающее меню у поля ввода цели
			Spinner:
				id: spiner_target
				text: 'URL'
				values: 'URL', 'DIRECT', 'LOGFILE', 'BULKFILE', 'REQUESTFILE', 'GOOGLEDORK', 'CONFIGFILE'
				on_text: root.change_lablle_on_target()

		BoxLayout:
			orientation: 'vertical'
			Label:
				id: lable_on_target
				text: 'Целевой URL (например, "http://www.site.com/vuln.php?id=1")'
#			поле ввода для цели
			TextInput:
				id: input_target
				text: 'Введите адрес или Ctrl+V'
				multiline: False


		BoxLayout:
			orientation: 'vertical'
			size_hint: 0.19, 1
			spacing: 5

			Button:
				text: 'Файл'
				on_release: root.show_files_target()
			Button:
				text: 'Вставить'
				on_press: root.paste_in_input_target()
			Button:
				text: 'Очистить'
				on_press: root.clear_input_target()



	TabbedPanelMain:

	BoxLayout:
		size_hint: 1, 0.07
		spacing: 50
		Button:
			text: 'Сформировать запрос'
			size_hint: 0.1, 1
			on_release: root.create_sqlmap_command()



